Host mac
    HostName 192.168.1.17
    User phill
    IdentityFile ~/.ssh/id_phill
    IdentitiesOnly yes
    ForwardAgent yes

# Proxmox host
Host kvatch
    HostName 192.168.1.101
    User root
    IdentityFile ~/.ssh/id_ed25519_homelab
    IdentitiesOnly yes

# Pi-hole in LXC
Host pihole
    HostName 192.168.1.100
    User root
    IdentityFile ~/.ssh/id_ed25519_homelab
    IdentitiesOnly yes

# Wildcard for Homelab devices
Host 192.168.1.* *.home
    User phill
    IdentityFile ~/.ssh/id_ed25519_homelab
    IdentitiesOnly yes
