$font = MesloLGS Nerd Font

general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    brightness = 0.6
    vibrancy = 0.17
}

label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p" | tr '[:upper:]' '[:lower:]'
    color = rgb(cad3f5)
    font_size = 96
    font_family = $font
    position = 0, 210
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %-d"
    color = rgb(a5adcb)
    font_size = 20
    font_family = $font
    position = 0, 130
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.3
    dots_center = true
    rounding = 8
    outer_color = rgb(8aadf4)
    inner_color = rgb(24273a)
    font_color = rgb(cad3f5)
    check_color = rgb(c6a0f6)
    fail_color = rgb(ed8796)
    fade_on_empty = false
    placeholder_text = <span foreground="##a5adcb">$USER</span>
    fail_text = <span foreground="##cad3f5">$FAIL ($ATTEMPTS)</span>
    position = 0, -40
    halign = center
    valign = center
}
